export const opinionComments = [
  "I recently sold a house via Heartland and while this can be a very stressful process, I felt 110% confident by partnering with them. They were candid, provided great feedback, helped explain clearly all details and managed the actual sale negotiation brilliantly. In addition, they were extremely responsive to every one of my questions, no matter how small. As I move forward to now BUY my next house, I am extremely certain Heartland will be the right partner to help me navigate this process.",
  "My wife and I had a dream of downsizing from our house in Cape Elizabeth into a small condo closer to where we work and play in Portland. Heartland's skilled team helped make that dream a reality. The sale went smoothly, and we just closed on an ideal new place we're excited to call home. Nobody  knows Portland and the peninsula better than them. They really listens to clients and go the extra mile with customer service, too.",
  "I've recommended the Heartland Real Estate Team to everyone I know. They are true professionals and excellent persons. I realize it won't always be this easy to sell your home, but I think you'd be hard pressed to find a better Realtor.",
  "I recently had the pleasure of working with Heartland when looking for my home. From day 1, they were extremely responsive and had great suggestions for homes to view based on what I was looking for. All throughout the negotiations and closing they were there quickly handling any issues that may have risen. If the time ever comes when I will be looking for a new home, there isn't any question on who my Realtor will be!",
  "I had the pleasure for working with Heartland. From start to finish they were very responsive, kind, and constant professionals. I look forward to the opportunity to work with Heartland Real Estate Team again.",
  "Heartland Real Estate Team worked with us from mid-August identifying the right property to meet our needs. They were always accessible and willing to make a variety of suggestions and options as we tried to. Are the right decision. We feel we have trustworthy agents, as well as friends! Thank you!",
  "Heartland sold my house and they helped me to buy a new one. They treat you like family, and work as hard as they can for you. If you are going to sell of buy a house I recommend you go with them. If I was ever going to sell or buy again they would be the first people I would call.",
  "We are so lucky that we found Heartland Real Estate Team, they made buying our first home an enjoyable and easy experience. Quick to respond and will do anything to help, we highly recommend them!"
]